import type { Metadata } from 'next';
import { CtaBand } from '@/components/CtaBand';
import { PageHero } from '@/components/PageHero';

export const metadata: Metadata = { title: 'How to Write a Website Brief', description: 'A practical website brief framework covering goals, audiences, content, technology, governance and acceptance criteria.', alternates: { canonical: '/insights/website-brief' } };

export default function ArticlePage() {
  return <main id="main-content">
    <PageHero eyebrow="Planning · Guide" title="How to write a website brief that prevents expensive ambiguity" lead="A useful brief creates alignment without pretending every solution is already known. It defines the problem, the evidence and the boundaries of a good outcome." image="strategy"/>
    <article className="article shell"><div className="article-body"><p>A website brief is not a shopping list of pages or visual preferences. It is a decision document. The strongest briefs give a team enough context to make good choices and enough constraints to know when the work is ready.</p><h2>1. Start with the business change</h2><p>Describe what should become meaningfully different: better-qualified enquiries, shorter sales explanations, easier publishing, stronger recruitment or lower operational risk. Name a baseline when one exists.</p><h2>2. Define priority audiences and situations</h2><p>“Everyone” is not an audience. Identify who has the highest-value problem, what prompts them to look, what they already know and what could prevent trust.</p><h2>3. Inventory evidence and content ownership</h2><p>List the proof you can substantiate, the content that exists, what must be created and who can approve it. Unowned content is one of the most common schedule risks.</p><h2>4. Make functional behavior explicit</h2><p>Document forms, integrations, permissions, error states, retention rules, consent, notifications and expected fallback behavior. A feature is incomplete until failure has a safe outcome.</p><h2>5. State the non-negotiable quality gates</h2><p>Include browser support, accessibility target, performance budgets, privacy obligations, search requirements, security controls and the exact acceptance process.</p><h2>6. Clarify operations after launch</h2><p>Name who owns hosting, domains, content, monitoring, updates, incident response and improvement. Launch is a transition of responsibility, not the end of it.</p><aside><strong>A concise brief should answer:</strong> Why now? For whom? What must change? What evidence do we have? What must the system do? What constraints apply? How will readiness be verified? Who owns it afterward?</aside></div></article>
    <CtaBand title="Need an experienced partner to shape the brief with you?"/>
  </main>;
}
