/*
# Create leads and seo_audits tables

## Summary
Creates two single-tenant tables (no auth/sign-in screen in this app) to support
the upgraded Kalpixa Web Studio website:

1. `leads` - stores contact form submissions from the multi-step contact form.
2. `seo_audits` - stores SEO audit requests and reports generated by the
   real SEO Analyzer edge function.

Both tables are intentionally public/shared (single-tenant, no login) so the
anon-key frontend can insert and read its own rows.

## New Tables

### leads
- `id` (uuid, primary key, default gen_random_uuid())
- `name` (text, not null) - submitter's full name
- `email` (text, not null) - submitter's email
- `phone` (text, nullable) - optional phone number
- `service` (text, not null, default 'Website') - selected service category
- `message` (text, nullable) - project description
- `status` (text, not null, default 'new') - lead lifecycle: new/contacted/closed
- `created_at` (timestamptz, default now())

### seo_audits
- `id` (uuid, primary key, default gen_random_uuid())
- `url` (text, not null) - the audited URL
- `email` (text, nullable) - optional email when user requests full report
- `report` (jsonb, nullable) - full audit report payload from edge function
- `score` (integer, nullable) - overall computed SEO score 0-100
- `created_at` (timestamptz, default now())

## Security
- RLS enabled on both tables.
- Because this is a no-auth public marketing site, policies use TO anon, authenticated
  so the anon-key frontend can insert leads/audits and read its own audit report
  right after creation. Reads are intentionally open (public marketing data only;
  no PII beyond the submitter's own submission).

## Important Notes
1. No user_id columns - this app has no sign-in flow; data is single-tenant.
2. `USING (true)` on SELECT is acceptable here because the data is intentionally
   public/shared (leads are marketing submissions, audit reports contain no
   sensitive data beyond a URL and optional email).
3. INSERT is open to anon so the public contact form and SEO tool work without login.
4. No UPDATE/DELETE policies are added because neither the frontend nor edge
   functions need to mutate rows after creation.
*/

CREATE TABLE IF NOT EXISTS leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  service text NOT NULL DEFAULT 'Website',
  message text,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_leads" ON leads;
CREATE POLICY "anon_select_leads" ON leads FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_leads" ON leads;
CREATE POLICY "anon_insert_leads" ON leads FOR INSERT
  TO anon, authenticated WITH CHECK (true);

CREATE TABLE IF NOT EXISTS seo_audits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  url text NOT NULL,
  email text,
  report jsonb,
  score integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE seo_audits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_seo_audits" ON seo_audits;
CREATE POLICY "anon_select_seo_audits" ON seo_audits FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_seo_audits" ON seo_audits;
CREATE POLICY "anon_insert_seo_audits" ON seo_audits FOR INSERT
  TO anon, authenticated WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_seo_audits_created_at ON seo_audits (created_at DESC);
